{
  "id": "2"
}

query GET_CATEGORY($id: ID!) {
  category(id: $id) {
    id
    title
  }
}


query GET_CATEGORIES {
  categories {
    id
    title
  }
}


mutation CREATE_CATEGORY($title: String! = "pastel de belém") {
  createCategory(data: {
    title: $title
  }) {
    id
    title
  }
}


# { "categoryId": "2",
#  "data": { "title": "sobremesas"}
# }

mutation UPDATE_CATEGORY($categoryId: ID!, $data: CategoryInput!) {
  updateCategory(categoryId: $categoryId, data: $data) {
    id
    title
  }
}


# {
#  "categoryId": "11"
# }

mutation DELETE_CATEGORY($categoryId: ID!) {
  deleteCategory(categoryId: $categoryId)
}
